name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install yarn
      run: npm install -g yarn

    - run: sudo apt-get update
    - run: sudo apt-get install -y libxkbfile-dev pkg-config libsecret-1-dev libxss1 dbus xvfb libgtk-3-0 libgbm1
    - run: sudo cp .github/workflows/xvfb.init /etc/init.d/xvfb
    - run: sudo chmod +x /etc/init.d/xvfb
    - run: sudo update-rc.d xvfb defaults
    - run: sudo service xvfb start

    - name: Bootstrap tests
      run: yarn test:ci

    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: ts-plugin
        path: ./dist
    - name: Upload build
      uses: actions/upload-artifact@v2
      with:
        name: vscode-plugin
        path: ./plugin/*.vsix
