name: Publish

on:
  push:
    tags: [ '*' ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install yarn
      run: npm install -g yarn
    - name: Install deps
      run: yarn
    - name: Build
      run: yarn build
    - name: Publish
      uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ secrets.NPM_TOKEN }}
    - name: Install VSCodep plugin deps
      run: yarn
      working-directory: ./plugin
    - name: Install lastest plugin
      run: yarn add ts-react-hooks-tools
      working-directory: ./plugin
    - name: Build VSCode plugin
      run: yarn build
      working-directory: ./plugin
    - name: Publish VSCode plugin
      run: yarn vsce publish -p ${{ secrets.AZURE_DEVOPS_ACCESS_TOKEN }}
      working-directory: ./plugin
